# Generated by Django 4.1.2 on 2022-10-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uid', models.CharField(max_length=30)),
                ('student_pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
