# Generated by Django 4.1.2 on 2022-10-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminLogin',
            new_name='StudentLogin',
        ),
    ]
