# Generated by Django 4.1.2 on 2022-10-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_adminlogin_studentlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
