# Generated by Django 4.1.2 on 2022-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_email', models.CharField(max_length=30)),
                ('qualifiaction', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('teacher_dob', models.CharField(max_length=30)),
                ('teacher_password', models.CharField(max_length=30)),
                ('teacher_phone', models.BigIntegerField()),
                ('teacher_photo', models.ImageField(upload_to='teacher/')),
                ('teacher_address', models.CharField(max_length=60)),
            ],
        ),
    ]
