# Generated by Django 4.1.2 on 2022-10-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_rename_experience_teacher_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_uid', models.CharField(max_length=30)),
                ('admin_pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
